### PR TITLE
Filter dusty bal incentives below 75 bucks over to the aura market.

### PR DESCRIPTION
**Pull request by Tritium-VLK**

### CODE REVIEW

**Comment by Tritium-VLK** [comment]
To test run action on 2024-08-01 data, and compare to #246.  Should be no 83 cent incentives.

**Comment by Tritium-VLK** [comment]
https://github.com/BalancerMaxis/protocol_fee_allocator/actions/runs/10207321473

**Comment by Tritium-VLK** [comment]
https://github.com/BalancerMaxis/protocol_fee_allocator/actions/runs/10207357076/job/28241960274

**Comment by Tritium-VLK** [comment]
Test Run with min amount as config.  Can close resulting PR and decide which of the above 2 to use this week.

**Comment by Tritium-VLK** [comment]
Worked

**Comment by Tritium-VLK** [comment]
If this looks good can reload the fee run in the multisig-ops repo with the contents of #287 before loading.

**Review by Xeonus — APPROVED** [review]
Deltas look good when comparing [original vs new run](https://www.diffchecker.com/0QixI7Ru/)

**Review by gosuto-inzasheru — APPROVED** [review]
looks great. test run checks out, sums of both runs is identical and deltas are accounted for properly

**Pull request merged**
