### PR TITLE
chore: Reactivate zkevm - Merge this when fees on zkEVM are swept

### PR DESCRIPTION
**Pull request by Tritium-VLK**

### CODE REVIEW

**Comment by Xeonus** [comment]
Before doing so, we need to authorize mimic smart vaults / make sure mimic infrastructure is up-to-date

**Comment by Xeonus** [comment]
BIP to authorize Mimic [now live](https://snapshot.org/#/balancer.eth/proposal/0xcf81e92a18e3cab3733c493bc5b1056807d229e4c92e4bcfbf3b1542976e9d81)

**Comment by Tritium-VLK** [comment]
Test Run

**Comment by Tritium-VLK** [comment]
Run successful.  This looks good to me.
https://github.com/BalancerMaxis/protocol_fee_allocator/pull/302/files

zkevm is there

**Comment by Tritium-VLK** [comment]
also @jalbrekt85 take note,.  We are reenabling zkevm.  Pls do so in v2 as well.

**Review by Xeonus — APPROVED** [review]
action run logs and output file in referenced PR look good. Thanks.

**Pull request merged**
